import { StyleSheet } from 'react-native';
import { COLORS, SPACING, FONT_SIZE, BORDER_RADIUS, COMMON_STYLES } from '../constants/theme';

const styles = StyleSheet.create({
  subHeader: { fontSize: 20, fontWeight: '200', marginTop: 45, marginBottom: 20, fontFamily: 'Roboto-Light', color: COLORS.text.primary },
  rowContainer: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 5 },
  label: { fontSize: 16, fontWeight: '600' },
	header: { 
    fontSize: 24, 
    fontWeight: 'bold', 
    marginBottom: 20,
    alignSelf: 'flex-start',
    width: '100%'
  },
  metricRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10, marginTop: 10 },
  collectingLabel: { flex: 0, fontSize: 16, fontWeight: '600', marginBottom: 10 },
  metricLabel: { flex: 1, fontSize: 16 },
  freqInput: {
    width: 60,
		borderRadius: 8,
		paddingTop: 8,
		paddingBottom: 8,
		textAlign: 'center',
    backgroundColor: COLORS.background.input,
	},
	unit: { fontSize: 16 },
  picker: {
    width: '100%',
    borderWidth: 1,
    borderRadius: 15,
    color: COLORS.text.primary,
    fontFamily: 'Roboto-Regular',
    fontSize: 14,
    backgroundColor: COLORS.background.input,
  },
	deviceItem: {
		padding: 10,
    backgroundColor: '#F0F0F0',
    borderRadius: 10,
    marginBottom: 10,
    marginTop: 10,
	},
	deviceItemConnected: {
		padding: 10,
    backgroundColor: '#E3F2FD',
    borderRadius: 10,
    marginBottom: 10,
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
	},
	deviceId: {
		fontSize: 12,
		color: '#666',
	},
	connectedStatus: {
		marginTop: 20,
		padding: 10,
		backgroundColor: '#E8F5E9',
		borderRadius: 8,
	},
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  connectionBanner: {
    backgroundColor: '#FF1B1C',
    flexDirection: 'row',
    alignItems: 'center',
    padding: SPACING.md,
    gap: SPACING.sm,
    paddingTop: 40,
  },
  connectionBannerText: {
    color: '#fff',
    fontSize: FONT_SIZE.sm,
    flex: 1,
  },
  connectionMessage: {
    color: '#FF1B1C',
    fontSize: FONT_SIZE.sm,
    textAlign: 'center',
    marginTop: SPACING.sm,
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: 'regular',
    marginBottom: 0,
    fontFamily: 'Roboto-Regular',
    color: COLORS.text.primary,
    marginTop: 20,
  },
  statusContainer: {
    padding: 15,
    borderRadius: 8,
    backgroundColor: '#E8F5E9',
    marginHorizontal: 20,
    marginBottom: 30,
  },
  statusContainerNotConnected: {
    backgroundColor: '#FFEBEE',
  },
  status: {
    fontSize: 16,
    color: '#2E7D32',
  },
  statusNotConnected: {
    color: '#C62828',
  },
  button: {
    backgroundColor: '#4CBAE6',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    alignSelf: 'center',
  },
  buttonDisabled: {
    borderColor: '#D5D2D2',
    backgroundColor: 'transparent',
    borderWidth: 1,
    shadowOpacity: 0,
    elevation: 0,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Roboto',
  },
  buttonTextDisabled: {
    color: '#D5D2D2',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 30,
    width: '85%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 16,
    fontFamily: 'Roboto',
    textAlign: 'center',
    marginBottom: 20,
    color: COLORS.text.primary,
  },
  input: {
    width: 80,
    height: 36,
    borderRadius: BORDER_RADIUS.sm,
    padding: SPACING.xs,
    textAlign: 'center',
    backgroundColor: COLORS.background.input,
  },
  buttonPrimary: {
    backgroundColor: '#4CBAE6',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 10,
    elevation: 2,
  },
  buttonPrimaryText: {
    color: '#fff',
    fontWeight: '600',
    fontFamily: 'Roboto',
    fontSize: 16,
  },
  cancelButton: {
    marginTop: 10,
    alignItems: 'center',
  },
  bottomButtonContainer: {
    paddingBottom: 40,
    alignItems: 'center',
  },
  contentContainer: {
    padding: SPACING.lg,
    paddingBottom: 40,
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    width: '100%',
  },
  recordInput: {
    alignItems: 'flex-end',
    gap: SPACING.sm,
  },
  recordLabel: {
    fontSize: FONT_SIZE.md,
    color: COLORS.text.primary,
    verticalAlign: 'middle',
    marginRight: 10,
  },
  categoryButtons: {
    ...COMMON_STYLES.row,
    flexWrap: 'wrap', 
    gap: SPACING.sm,
    justifyContent: 'center',
    marginBottom: SPACING.md,
  },
  categoryButton: {
    padding: SPACING.sm,
    borderRadius: BORDER_RADIUS.sm,
    backgroundColor: COLORS.secondary,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  categoryButtonSelected: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  categoryButtonDisabled: {
    borderColor: '#D5D2D2',
    backgroundColor: 'transparent',
    shadowOpacity: 0,
    elevation: 0,
  },
  categoryText: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.text.primary,
  },
  categoryTextSelected: {
    color: COLORS.text.light,
  },
  categoryTextDisabled: {
    color: '#D5D2D2',
  },
  chartContainer: {
    height: 300,
    ...COMMON_STYLES.card,
    marginBottom: SPACING.md,
    width: '100%',
    overflow: 'hidden',
  },
  tallChartContainer: {
    height: 350,
  },
  chartHeader: {
    ...COMMON_STYLES.row,
    justifyContent: 'space-between',
    marginBottom: SPACING.sm,
    padding: SPACING.sm,
  },
  chartTitle: {
    ...COMMON_STYLES.subtitle,
  },
  showDataButton: {
    ...COMMON_STYLES.button,
  },
  showDataButtonText: {
    ...COMMON_STYLES.buttonText,
  },
  modalTableContainer: {
    backgroundColor: '#fff',
    borderRadius: BORDER_RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: SPACING.md,
    padding: SPACING.sm,
  },
  modalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  modalHeaderCell: {
    flex: 1,
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    color: COLORS.text.primary,
    textAlign: 'center',
  },
  modalCell: {
    flex: 1,
    fontFamily: 'Roboto',
    color: COLORS.text.primary,
    textAlign: 'center',
  },
  modalInfoText: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.text.secondary,
    fontFamily: 'Roboto',
    lineHeight: 20,
  },
  modalBoldText: {
    fontWeight: 'bold',
    color: COLORS.text.primary,
  },
  modalSectionTitle: {
    fontSize: FONT_SIZE.md,
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    color: COLORS.text.primary,
    marginTop: SPACING.md,
    marginBottom: SPACING.sm,
  },
  dateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    fontSize: FONT_SIZE.sm,
  },
  dateIcon: {
    marginRight: SPACING.xs,
  },
  chartScrollContent: {
    flexGrow: 1,
    paddingRight: SPACING.md,
  },
  chartWrapper: {
    flex: 1,
    minWidth: '100%',
    marginLeft: -SPACING.md,
    height: 250,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SPACING.sm,
  },
  checkboxLabel: {
    fontSize: FONT_SIZE.md,
    marginLeft: SPACING.sm,
    color: COLORS.text.primary,
  },
  dateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: SPACING.md,
    justifyContent: 'space-between',
  },
  dateInput: {
    width: '45%',
    padding: SPACING.sm,
    borderRadius: BORDER_RADIUS.sm, 
    backgroundColor: COLORS.background.input,
    fontFamily: 'Roboto-Regular',
  },
  dateInputContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dateNavigation: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.md,
  },
  dateText: {
    fontSize: 22,
    color: COLORS.text.primary,
    fontFamily: 'Roboto-Light',
  },
  recordInfo: {
    alignItems: 'center',
  },
  recordIDText: {
    fontSize: FONT_SIZE.md,
    color: COLORS.text.secondary,
    fontFamily: 'Roboto-Regular',
    marginVertical: 2,
    marginBottom: 30,
  },
  sleepTimeCircle: {
    width: 160,
    height: 160,
    borderRadius: 80,
    borderWidth: 6,
    borderColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.background,
    padding: SPACING.sm,
    marginRight: SPACING.lg,
  },
  sleepTimeText: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.text.primary,
    fontFamily: 'Roboto-Light',
    textAlign: 'center',
  },
  availableMetricsContainer: {
    justifyContent: 'center',
    height: 160,
    gap: 5,
    paddingLeft: SPACING.lg,
  },
  metricRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
    marginTop: 5,
  },
  availabilityDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  metricText: {
    fontSize: FONT_SIZE.sm,
    fontFamily: 'Roboto-Regular',
  },
  flexItem: {
    flex: 1,
  },
  calendarContainer: {
    paddingHorizontal: SPACING.lg,
  },
});

export default styles;