import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  subHeader: { fontSize: 18, fontWeight: '500', marginTop: 20, marginBottom: 10 },
  rowContainer: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 5 },
  label: { fontSize: 16, fontWeight: '600' },
	header: { fontSize: 28, fontWeight: 'bold', marginBottom: 20 },
  metricRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  metricLabel: { flex: 1, fontSize: 16 },
  freqInput: {
  width: 60,
		borderWidth: 1,
		borderColor: '#ccc',
		borderRadius: 8,
		padding: 6,
		textAlign: 'center',
		marginHorizontal: 8,
	},
	unit: { fontSize: 16 },
	saveButton: {
		backgroundColor: '#4CBAE6',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginVertical: 20,
		padding: 20,
	},
	saveButtonText: {
		color: '#fff',
		fontSize: 16,
		fontWeight: '600',
	},
	deviceItem: {
		padding: 10,
		borderBottomWidth: 1,
		borderBottomColor: '#ddd',
	},
	deviceId: {
		fontSize: 12,
		color: '#666',
	},
	connectedStatus: {
		marginTop: 20,
		padding: 10,
		backgroundColor: '#E8F5E9',
		borderRadius: 8,
	},
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
		padding: 40,
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  statusContainer: {
    padding: 15,
    borderRadius: 8,
    backgroundColor: '#E8F5E9',
    marginHorizontal: 20,
    marginBottom: 30,
  },
  statusContainerNotConnected: {
    backgroundColor: '#FFEBEE',
  },
  status: {
    fontSize: 16,
    color: '#2E7D32',
  },
  statusNotConnected: {
    color: '#C62828',
  },
  button: {
    backgroundColor: '#007AFF',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  buttonDisabled: {
    backgroundColor: '#BDBDBD',
    elevation: 0,
    shadowOpacity: 0,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 30,
    width: '85%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 16,
    fontFamily: 'Roboto',
    textAlign: 'center',
    marginBottom: 20,
    color: '#333',
  },
  input: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    padding: 10,
    marginBottom: 20,
    fontFamily: 'Roboto',
  },
  buttonPrimary: {
    backgroundColor: '#4CBAE6',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 10,
    elevation: 2,
  },
  buttonPrimaryText: {
    color: '#fff',
    fontWeight: '600',
    fontFamily: 'Roboto',
    fontSize: 16,
  },
  cancelButton: {
    marginTop: 10,
    alignItems: 'center',
  },
  bottomButtonContainer: {
    paddingBottom: 40,
    alignItems: 'center',
  },
});

export default styles;